# Generated by Django 4.2.11 on 2025-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_is_booked_seat_booking_status_seat_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='booking_status',
            new_name='is_booked',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
