# Generated by Django 4.2.11 on 2025-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_booking_date_movie_showing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='showing_date',
            field=models.DateTimeField(),
        ),
    ]
